export { default as Home } from './Home'
export { default as Predict } from './Predict' 
export { default as Event } from './Event'
export { default as Calendar } from './Calendar'
export { default as Weights } from './Weights'
export { default as Fighters } from './Fighters'